services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_ADMIN:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_ADMIN_PASSWORD:-postgrespassword}
      POSTGRES_NONADMIN_PASSWORD: ${POSTGRES_NONADMIN_PASSWORD:-postgresnonadminpassword}
      POSTGRES_MULTIPLE_DATABASES: keycloak, hololinked
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
    command: [
      "postgres",
      "-c listen_addresses=*",
    ]
    # "-c max_connections=200",
    # "-c max_worker_processes=2",
    # "-c max_parallel_workers=2",
    # "-c max_parallel_workers_per_gather=1",
    # "-c shared_buffers=256MB",
    # "-c effective_cache_size=768MB",
    # "-c maintenance_work_mem=64MB",
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./scripts/init-db:/docker-entrypoint-initdb.d
    restart: unless-stopped

  dbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: dbeaver
    environment:
      CB_ADMIN_NAME: ${CLOUDBEAVER_ADMIN:-admin}
      CB_ADMIN_PASSWORD: ${CLOUDBEAVER_ADMIN_PASSWORD:-adminpassword}
    ports:
      - "8978:8978"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./conf/dbeaver-initial-data-sources.conf:/opt/cloudbeaver/conf/initial-data-sources.conf
      - ./data/dbeaver:/opt/cloudbeaver/workspace
    restart: unless-stopped
    depends_on:
      - postgres  

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.3
    container_name: keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: host.docker.internal
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: ${POSTGRES_NONADMIN_PASSWORD:-postgresnonadminpassword}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-adminpassword}
    command: start-dev
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./data/keycloak:/opt/keycloak/data
    restart: unless-stopped
    depends_on:
      - postgres

  reverse-proxy:
    image: nginx:latest
    container_name: reverse-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs/server.crt:/etc/nginx/server.crt:ro
      - ./certs/server.key:/etc/nginx/server.key:ro
    depends_on:
      - keycloak
      - dbeaver
    restart: unless-stopped