[project]
name = "daq-system-infrastructure"
version = "0.1.0"
description = "set of python tools that faciliate IT infrastructure installation"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.16.5",
    "dotenv>=0.9.9",
    "pip>=25.2",
    "psycopg2-binary>=2.9.11",
    "sqlalchemy-utils>=0.42.0",
    "hololinked>=0.3.11",
    "pydantic>=2.7.0"
]

[project.scripts]
create_dotenv = "create_dotenv:main"
ctl = "cli.ctl:main"

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["cli"]
py-modules = ["create_dotenv"]

