"""v_0_3_5_base

Revision ID: c1ed2b2913b8
Revises:
Create Date: 2026-02-21 23:20:54.118997

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlalchemy_utils  # noqa: F401
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c1ed2b2913b8"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "properties",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("serialized_value", sa.LargeBinary(), nullable=False),
        sa.Column("thing_id", sa.String(), nullable=False),
        sa.Column("thing_class", sa.String(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.Column("content_type", sa.String(), nullable=False, server_default="application/json"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "things",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("thing_id", sa.String(), nullable=False),
        sa.Column("thing_class", sa.String(), nullable=False),
        sa.Column("script", sa.String(), nullable=False),
        sa.Column("init_kwargs", sa.JSON(), nullable=True),
        sa.Column("server_id", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("thing_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("things")
    op.drop_table("properties")
    # ### end Alembic commands ###
