"""base

Revision ID: 35bddd5382da
Revises:
Create Date: 2025-10-11 17:51:15.677099

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = "35bddd5382da"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "properties",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("serialized_value", sa.LargeBinary(), nullable=False),
        sa.Column("thing_class", sa.String(), nullable=False),
        sa.Column("thing_id", sa.String(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "things",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("class_name", sa.String(), nullable=False),
        sa.Column("script", sa.String(), nullable=False),
        sa.Column("init_kwargs", sa.JSON(), nullable=True),
        sa.Column("server_id", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("things")
    op.drop_table("properties")
    # ### end Alembic commands ###
