[project]
name = "daq-system-infrastructure"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.16.5",
    "hololinked>=0.3.3",
    "sqlalchemy-utils>=0.42.0",
]
